N1: 
EQU 10
L1: EQU 1
L2: EQU 0
SECAO TEXTO
IF L1
LOAD SPACE ;faz esta operação se L1 for verdadeiro
IF L2
INPUT SPACE ;faz esta operação se L2 for verdadeiro
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS
STORE NEW_DATA

MULT DOIS ;aAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
STORE TMP_DATA 
LOAD OLD_DATA
SUB TMP_DATA
IF N1
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA, OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECAO DADOS
DOIS: CONST N1
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE


